### ISSUE TITLE
Image Tracking on Web Cam

### ISSUE THREAD

**Issue by pluka073** [rgend797/COMP3504-group-project#18]
- [ ]  Create an Image that camera can find and display AR
- [ ] Access AR camera and ensure image tracking works
- [ ] Present Karel on a image.

**Comment by jbant729** [comment]
reviewed by Jan, after testing on Friday, Karel and scene was presented onto the image with AR
